[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "forge-std/=lib/forge-std/src/"
]
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 200
chain_id = 11155111

[rpc_endpoints]
sepolia = "https://eth-sepolia.g.alchemy.com/v2/demo"
sepoliaTestnet = "https://rpc.sepolia.org"
bnbTestnet = "https://bsc-testnet.public.blastapi.io"
bsctest = "https://data-seed-prebsc-1-s1.binance.org:8545"
bnbMainnet = "${BNB_MAINNET_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
bnbTestnet = { key = "${ETHERSCAN_API_KEY}" }
